### ISSUE TITLE
Got a message with no "From" field

### ISSUE THREAD

**Issue by thefinn93** [AccelerateNetworks/NumberSearch#326] opened 2023-04-28 19:47 UTC
As a downstream client, we received a webhook call with an empty From. You can find this in the logs under ID `efe21498-8cc0-49d0-a6ef-4473d8475670`.

**Comment by uncheckederror** [comment] 2023-04-28 20:31
@thefinn93 Thank you for this bug report. I'll update this thread when I have a root cause and resolution.

**Comment by uncheckederror** [comment] 2023-04-28 20:33
@thefinn93 do you know what the expected From address was for this incoming message?

**Comment by thefinn93** [comment] 2023-04-28 20:34
@danry25 might know

**Comment by uncheckederror** [comment] 2023-04-28 21:06
Found a list of short codes from CenturyLink here: https://www.centurylink.com/home/help/account/sms-terms-and-conditions.html

**Comment by thefinn93** [comment] 2023-04-28 21:22
@danry25 confirmed via text that it was a centurylink short code.

**Comment by uncheckederror** [comment] 2023-04-28 22:55
Alright so the issue was that short codes weren't getting parsed correctly. A new build is live that I believe fixes this bug. I have also added a test for the incoming SMS message endpoint to verify that we don't run into this issue again.

**Comment by danry25** [comment] 2023-04-30 06:43
I verified that this issue is resolved on the NumberSearch side of the equation, but uncovered a bug with OrgSMS's number normalization prefixing a 1 to shortcode numbers. Closing this issue.

**Closed by danry25** 2023-04-30 06:43 UTC
Labels: bug, internal
