### ISSUE TITLE
E911 Address Update through Owned Numbers

### ISSUE THREAD

**Issue by sewcialite** [AccelerateNetworks/NumberSearch#371] opened 2023-07-25 20:47 UTC
I was following the ticketing guide to update E911 addresses for clients through Owned Numbers. A client's address information did not pop up where it was supposed to. Dan said to file a ticket because it seems there may be an existing modification you can't replace it with a new address when the client moves

**To Reproduce**
1. Go to [Owned Numbers](https://ops.acceleratenetworks.com/Home/OwnedNumbers/), search for the affected phone number, 4255765190
2. Click on the yellow edit button
3. Space to edit the address should appear below E911 Registration but does not. 
4. See error: 
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/87674023/8aad85a0-aa39-4f65-ab35-fad83e51d739)

**Expected behavior**
1. Go to [Owned Numbers](https://ops.acceleratenetworks.com/Home/OwnedNumbers/), search for the affected phone number, 4255215201
2. Click on the yellow edit button
3. See expected result below E911 Address Registration:
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/87674023/7cc73444-a65c-44ac-99f4-151e16ebcd46)

**Comment by uncheckederror** [comment] 2023-07-26 20:30
Thanks for filing this bug. I will investigate.

**Comment by uncheckederror** [comment] 2023-07-27 01:38
Okay, I have updated the page to show the Registration form with a warning even when the Owned Number already has an active E911 Registration record. It should look like this now:

![image](https://github.com/AccelerateNetworks/NumberSearch/assets/11726956/86111c79-1c83-4abc-b0f4-778bc69af964)

**Comment by sewcialite** [comment] 2023-07-27 02:14
Looks great! Thank you so much for your help

**Comment by uncheckederror** [comment] 2023-07-28 00:02
Hey @sewcialite can you verify that the issue is resolved and that you were able to update the E911 Registration for [4255765190](https://ops.acceleratenetworks.com/Home/OwnedNumbers/4255765190) so we can close this issue?

**Comment by uncheckederror** [comment] 2023-07-29 00:21
Closing this for now as the issue is resolved for this specific E911 client.

**Closed by uncheckederror** 2023-07-29 00:21 UTC
Labels: bug, internal
