### ISSUE TITLE
Putting a suite number in the Address field causes address suggestions to be hidden

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#196] opened 2021-06-24 23:50 UTC
**Describe the bug**
When I input an address in Ops, say 411 S Dawson St STE A, I see the datalist id=addressoptions is generated with multiple valid addresses, but the dropdown is not displayed to the user. This bug appears to also affect the main website
**To Reproduce**
1. Go to acceleratenetworks.com
2. Click on checkout (with objects in your cart)
3. Open Dev tools, look at Console
4. Enter a partial address with the unit type and number at the end, like 411 S Dawson St STE A and see how no suggestions are shown despite a datalist being retrieved containing multiple valid options.

**Expected behavior**
Show the possible addresses, perhaps put the trailing data on the right side of the user input into the Unit Number field?

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Browser: Chromium Version 90.0.4430.93 (Developer Build) built on Debian 10.9, running on Debian 10.9 (64-bit)
 - Browser: Firefox 78.10.0esr (64bit)

**Comment by uncheckederror** [comment] 2021-06-25 02:38
This is a duplicate of #193. The input filters the datalist elements based on the text currently in the input box by exact or partial matching. If you've entered incorrect characters all of the results in the datalist will be hidden by this filtering.

**Comment by uncheckederror** [comment] 2021-06-29 04:06
To solve this issue we'd have to quit using the datalist HTML element.

**Comment by uncheckederror** [comment] 2021-07-02 05:47
@danry25 please review and close this, if you approve.

**Closed** 2021-07-10 03:49 UTC
Labels: bug, done, external
