### ISSUE TITLE
Failed To Create Tax Rate!!!

### ISSUE THREAD

**Issue by kylek206** [AccelerateNetworks/NumberSearch#156] opened 2021-02-22 21:26 UTC
**Describe the bug**
I went to go create a new Tax rate and it Failed to convert to our billing system.

**To Reproduce**
1. Go to 'ops backend page'
2. Click on 'Tax Rates'
3. Scroll down to 'Scroll down and enter address (Sammamish Tax Rate)'
4. See error 'Create Tax Rate and then you see error'

**Expected behavior**
I should be able to enter any address and or zipcode that should create a tax rate that isn't in our system or is able to match what we have in our system. 

**Screenshots**
![Failed to Create Tax Rate (Sammamish, 98075) ](https://user-images.githubusercontent.com/73979802/108772052-612a7b80-7511-11eb-830f-064bb178f106.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by uncheckederror** [comment] 2021-02-22 21:34
Hey Kyle thanks for reporting this bug! I apricate the work you're doing. We're currently having trouble communicating with the State's Tax Rates API. Dan will update you when it is resolved.

**Comment by uncheckederror** [comment] 2021-02-22 21:37
Duplicate of #149

**Comment by uncheckederror** [comment] 2021-02-22 22:18
@kylek206 I've released a new version of the app that fixes this issue, can you try it again?

**Comment by kylek206** [comment] 2021-02-23 01:52
@uncheckederror I tried again and gave me the same error message!

**Comment by uncheckederror** [comment] 2021-02-24 18:04
@kylek206 I have added a bunch of retry logic, it may take longer to process, but hopefully it will work for you now. Please try it again and let me know. Thanks!

**Closed** 2021-02-25 18:15 UTC
Labels: bug, duplicate, internal
